
# frontend-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: mywebpanda-frontend
  ports:
    - protocol: TCP
      port: 2020
      targetPort: 2020
  type: LoadBalancer

