# frontend-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mywebpanda-frontend
  template:
    metadata:
      labels:
        app: mywebpanda-frontend
    spec:
      containers:
      - name: mywebpanda-frontend
        image: mywebpanda-frontend:latest
        ports:
        - containerPort: 2020
